"""add password and check

Revision ID: 04461d8f3756
Revises: 197ca3500e66
Create Date: 2018-08-06 11:10:08.420701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04461d8f3756'
down_revision = '197ca3500e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
