"""confirmed

Revision ID: 88708a0b649c
Revises: 9d655893554d
Create Date: 2018-08-06 18:33:03.185091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88708a0b649c'
down_revision = '9d655893554d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
